### ISSUE TITLE
Cannot start exporter: unexpected end of JSON input

### ISSUE THREAD

**Issue by yasharne** [cafebazaar/keepalived-exporter#44]
Hi
When I try to run the exporter, I get this fatal error:
```sh
FATA[0000] Error unmarshalling signum result             error="unexpected end of JSON input" signal=DATA
```
I'm using version `1.0.3` of the exporter on centos7 and keepalived version `1.3.5`

**Comment by clwluvw** [comment]
@yasharne Can you please share the result of this command:
```bash
keepalived --signum=DATA
```

**Comment by yasharne** [comment]
@clwluvw I get this error on `--signum=DATA`:
```
flag provided but not defined: -signum
```
Using `-signum=DATA` also has a same error:
```
flag provided but not defined: -signum
```

**Comment by clwluvw** [comment]
@yasharne I seems `--signum` is introduced in keepalived v1.3.8
You can update you keepalived to fix this issue.

**Comment by clwluvw** [comment]
We will also check to see if we can support these versions or not
CC: @mehdy
