### ISSUE TITLE
error running the binary

### ISSUE THREAD

**Issue by pvyaka01** [cafebazaar/keepalived-exporter#56]
Downloaded version 1.0.3
OS: Red Hat Enterprise Linux Server release 7.9 (Maipo)

 ./keepalived-exporter
FATA[0000] Error unmarshalling signum result             error="unexpected end of JSON input" signal=DATA

Thanks

**Comment by clwluvw** [comment]
@pvyaka01 Can you please share your keepalived version?

**Comment by pvyaka01** [comment]
Downloaded version 1.0.3

**Comment by clwluvw** [comment]
@pvyaka01 Please use newly release of Keepalived Exporter v1.1.0. This version supports Keepalived < v1.3.8

**Comment by pvyaka01** [comment]
Thanks for fixing it quickly! Appreciate the help. 

1.1.0 version seems to work.
